# Generated by Django 3.1.2 on 2021-02-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolus_pal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolus',
            name='blood_sugar',
            field=models.IntegerField(),
        ),
    ]
