# Generated by Django 3.1.2 on 2021-02-16 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bolus_pal', '0002_auto_20210209_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
