# Generated by Django 3.1.2 on 2021-02-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolus_pal', '0003_bolus_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('carbs', models.IntegerField(default=0)),
                ('servings', models.IntegerField(default=0)),
                ('bolus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bolus_pal.bolus')),
            ],
        ),
    ]
