# Generated by Django 3.1.2 on 2021-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolus_pal', '0004_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolus',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
